Makefile Compilation Fix (#490)
* renamed boolean to bool

* Rename byte to uint8_t

* Fix compilation error: 'NULL' was not declared in this scope

* Always typedef RoReg and RwReg for the AVR platform

* Include stdlib.h if abs() is not available
This is required as Arduino.h #define's its own abs() makro. Outside of Arduino environments stdlib is required.
Also see: https://github.com/arduino/Arduino/issues/6684

* Replace digitalWrite() with Pin Class by FastLed

* Include string.h for memset function
This include is normally done by Arduino.h but still required for makefile environments
$ grep string.h . -r
./Arduino.h:#include <string.h>

* Include math.h for pow()
math.h is normally included by Arduino.h but required for a makefile build
$ grep math.h . -r
./Arduino.h:#include <math.h>